### PR TITLE
easy.go: update identifier to C.struct_curl_slist

### LINKED ISSUE #67: Cannot compile after march 14 update
/go/src/github.com/andelf/go-curl/easy.go:408:22: identifier "_Ctype_struct_curl_slist" may conflict with identifiers generated by cgo

### PR DESCRIPTION
**Pull request by rilutham**
@andelf Please review this PR for Fixes #67

### CODE REVIEW

**Comment by codecyclist** [comment]
I can confirm that this resolves the `/easy.go:408:22: identifier "_Ctype_struct_curl_slist" may conflict with identifiers generated by cgo` issue.

Would love to have this merged if no contraindications are present.

**Comment by walshbm15** [comment]
I ran into this same issue on Go version 1.13, and confirm this also resolves the issue there. 

Any indication where this stands? Would also love to see this merged.

**Comment by abhinavdangeti** [comment]
Any updates here? This fix addresses problems we're seeing with GOVERSION > 1.11.6

**Comment by andelf** [comment]
Thanks

**Pull request merged**
