### PR TITLE
add TLS1.3 support

### PR DESCRIPTION
**Pull request by jhfeng**
Adding TLS1.3 option in go-curl

### CODE REVIEW

**Comment by jhfeng** [comment]
@andelf are you the current maintainer for go-curl ? Please review this simple PR.

**Comment by andelf** [comment]
Thanks. :)

**Comment by andelf** [comment]
It's not as that simple.
backward compatibility should be maintained.

**Comment by jhfeng** [comment]
> It's not as that simple.
> backward compatibility should be maintained.

could you explain why adding TLS1.3 breaks backward compatibility ? and what's best why to get TLS1.3 support ?

**Comment by andelf** [comment]
It's been a long time(years) since I last edited these codes(actually wrote code in golang). I will deal with the feature requests / PRs this weekend.

It might be solved by  `compatgen.py` & `compat.h`.

**Comment by andelf** [comment]
This repo seems to support from curl `7.10.1`, which is very old.

**Comment by jhfeng** [comment]
@andelf do you plan to actively maintain this repo ? I'm looking at it if I can use it in our service, but we need it to support new version of curl.

**Comment by andelf** [comment]
I haven't written any golang code for years. :)
The maintain status might be terrible now.
To actively maintain the repo, first, I need to look into the historical code generating tools.

I will resolve your issue this weekend. 

The latest `libcurl` version update in this repo is `7.51.0`, in 2016.
The latest `libcurl` version is `7.71.0`.

**Pull request merged**
